dataset:
  path: data/ZINC
  node_attr_dim: 28 # actually 21 in Zinc-12k, 28 in Zinc-full
  edge_attr_dim: 4
  inmemory_transform:
    poly:
      poly_method: rrwp
model:
  name: ppgn
  node_encoder: type_dict
  edge_encoder: type_dict
  loop_encoder: linear
  pair_encoder: linear
  hidden_dim: 80
  num_layers: 10
  mlp_depth: 2
  pooling: avg
  drop_prob: 0.0
  jk_mode: last
  task_type: graph_regression
  num_tasks: 1
  norm_type: batch
  act_type: relu
  max_num_nodes: 38
train:
  runs: 5
  save_dir: results/zincfull
  batch_size: 256
  num_workers: 0
  lr: 1e-3
  min_lr: 1e-6
  weight_decay: 1e-5
  num_warmup_epochs: 50
  num_epochs: 2000
  optimizer: AdamW
  scheduler: cosine_with_warmup
