dataset:
  path: data/TUD
  dataname: null
  poly_dim: 18
  inmemory_transform:
    poly:
      poly_method: rrwp
    2fwl_connsp: {}
  follow_batch: [pair_x]
model:
  name: sppgn1
  node_encoder: linear
  edge_encoder: linear
  loop_encoder: linear
  pair_encoder: linear
  hidden_dim: 64
  num_layers: 4
  mlp_depth: 2
  pooling: avg
  drop_prob: 0
  jk_mode: last
  task_type: graph_classification
  num_tasks: 1
  norm_type: batch
  act_type: relu
train:
  runs: 10
  save_dir: results/tud
  batch_size: 32
  num_workers: 0
  lr: 1e-3
  min_lr: 1e-6
  weight_decay: 0
  num_warmup_epochs: 5
  num_epochs: 100
  optimizer: AdamW
  scheduler: cosine_with_warmup
log:
  monitor: val/acc
  monitor_mode: max
