dataset:
  path: data/ZINC
  node_attr_dim: 21 # actually 21 in Zinc-12k, 28 in Zinc-full
  edge_attr_dim: 4
  poly_dim: 22
  inmemory_transform:
    poly:
      poly_method: rrwp
    2fwl_connsp: {}
  follow_batch: [pair_x]
model:
  name: sppgn1
  node_encoder: type_dict
  edge_encoder: type_dict
  loop_encoder: poly
  pair_encoder: poly
  hidden_dim: 80
  num_layers: 10
  mlp_depth: 2
  pooling: sum_avg
  drop_prob: 0.0
  jk_mode: last
  task_type: graph_regression
  num_tasks: 1
  norm_type: batch
  act_type: relu
  use_sqrt: true
train:
  runs: 5
  save_dir: results/zinc
  batch_size: 32
  num_workers: 0
  lr: 1e-3
  min_lr: 1e-6
  weight_decay: 1e-5
  num_warmup_epochs: 50
  num_epochs: 2000
  optimizer: AdamW
  scheduler: cosine_with_warmup
